name: CI/CD

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt

  unit_test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
      - name: Test
        run: |
          python -m pytest ${{ github.workspace }}/Test/TestSuite/UnitTestSuite/test_suite.py
  
  selenium_test:
    needs: unit_test
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
      - name: Test
        run: |
          export FLASK_APP=app.py
          export FLASK_ENV=development
          flask run &
          python -m pytest ${{ github.workspace }}/Test/TestSuite/SeleniumTestSuite/selenium_test_suite.py
          fg
    
        
